services:
  db:
    container_name: kalianak_db
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - kalianak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kalianak_internal

  backend:
    container_name: kalianak_backend
    build: ./backend
    restart: always
    env_file:
      - .env
    volumes:
      - kalianak_media:/app/media
      - kalianak_static:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kalianak_internal
      - webproxy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_DEBUG: "False"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.kalianak-backend.rule=Host(`api-pos.ikanbakarkalianak.store`)"
      - "traefik.http.routers.kalianak-backend.entrypoints=websecure"
      - "traefik.http.routers.kalianak-backend.tls.certresolver=myresolver"
      - "traefik.http.services.kalianak-backend.loadbalancer.server.port=8000"

  frontend:
    container_name: kalianak_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - backend
    networks:
      - kalianak_internal
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.kalianak-pos.rule=Host(`pos.ikanbakarkalianak.store`)"
      - "traefik.http.routers.kalianak-pos.entrypoints=websecure"
      - "traefik.http.routers.kalianak-pos.tls.certresolver=myresolver"
      - "traefik.http.services.kalianak-pos.loadbalancer.server.port=80"

  web_frontend:
    container_name: kalianak_web_frontend
    build:
      context: ./web_frontend
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - backend
    networks:
      - kalianak_internal
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.kalianak-web.rule=Host(`www.ikanbakarkalianak.store`)"
      - "traefik.http.routers.kalianak-web.entrypoints=websecure"
      - "traefik.http.routers.kalianak-web.tls.certresolver=myresolver"
      - "traefik.http.services.kalianak-web.loadbalancer.server.port=80"

networks:
  kalianak_internal:
  webproxy:
    external: true

volumes:
  kalianak_db_data:
  kalianak_media:
  kalianak_static:
